apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
        env:
        - name: POSTGRES_DB
          value: contact_db
        - name: POSTGRES_USER
          value: testing
        - name: POSTGRES_PASSWORD
          value: testing
  volumeClaimTemplates:
  - metadata:
      name: postgresdb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
