apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # The Init Container runs to completion BEFORE the main container starts
      initContainers:
      - name: db-migration
        image: roshank8848/threetier-backend:0.0.1
        command: ["sh", "-c", "alembic upgrade head"]
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://testing:testing@postgres:5432/contact_db"
      
      containers:
      - name: backend
        image: roshank8848/threetier-backend:0.0.1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://testing:testing@postgres:5432/contact_db"
        # The main container now only worries about running the app
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]

